# Generated by Django 6.0.2 on 2026-02-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_exam_proctoringlog_question_choice_examenrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_profiles/'),
        ),
    ]
