# Generated by Django 6.0.2 on 2026-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_correct_answer_alter_question_question_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('exam', 'order'), name='unique_question_order_per_exam'),
        ),
    ]
