# Generated by Django 6.0.2 on 2026-02-25 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_unique_question_order_per_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examresult',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examresult',
            name='wrong_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_submitted', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('face_verified', models.BooleanField(default=False)),
                ('face_verification_note', models.CharField(blank=True, max_length=255)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('awarded_marks', models.FloatField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exams.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_answers', to='exams.choice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'question'), name='unique_answer_per_question_per_session')],
            },
        ),
    ]
